c="THE CALCULATOR"
print(c)
a=int(input("Enter your first number: "))
b=int(input("Enter your second number: "))
print("Addition =",a+b)
print("Subtraction =",a-b)
print("Multiplication =",a*b,type(a*b))
print("Division =",a/b,type(a/b))
print("Exponent =",a**b)
print("Floor Division =",a//b)
print("Remainder =",a%b)